@startuml

left to right direction
actor User

rectangle   HotelManagementSystem {
    usecase "Make Reservation" as UC1
    usecase "Display Room" as UC2
    usecase "Display Reservation" as UC3

    User --> (UC1)
    User --> (UC2)
    User --> (UC3)
}

@enduml